export const Navlinks = [
    {
        id:1,
        name: "Home",
        Link: "",
    },
    {
        id:2,
        name: "Contact",
        Link: "Contact"
    },
    {
        id:3,
        name: "About",
        Link: "About"
    },
    {
        id:4,
        name: "Careers",
        Link: "Careers"
    },
    
    {
        id:5,
        name: "Services",
        Link: "Services"
    },
    
]
export const Products = [
    { id: 1, name: "Mechanical Keyboard", link: "mechanical-keyboard" },
    { id: 2, name: "Wireless Mouse", link: "wireless-mouse" },
    { id: 3, name: "4K Monitor", link: "4k-monitor" },
    { id: 4, name: "USB-C Hub", link: "usb-c-hub" },
    { id: 5, name: "Webcam HD", link: "webcam-hd" },
    { id: 6, name: "Noise Cancelling Headphones", link: "noise-cancelling-headphones" },
    { id: 7, name: "Laptop Stand", link: "laptop-stand" },
    { id: 8, name: "External SSD", link: "external-ssd" },
    { id: 9, name: "Thunderbolt Dock", link: "thunderbolt-dock" },
    { id: 10, name: "Gaming Chair", link: "gaming-chair" },
    { id: 11, name: "LED Desk Lamp", link: "led-desk-lamp" },
    { id: 12, name: "Bluetooth Speaker", link: "bluetooth-speaker" },
    { id: 13, name: "Smart Watch", link: "smart-watch" },
    { id: 14, name: "Graphics Tablet", link: "graphics-tablet" },
    { id: 15, name: "Stream Deck", link: "stream-deck" },
    { id: 16, name: "Microphone", link: "microphone" },
    { id: 17, name: "Ring Light", link: "ring-light" },
    { id: 18, name: "Ergonomic Chair", link: "ergonomic-chair" },
    { id: 19, name: "Standing Desk", link: "standing-desk" },
    { id: 20, name: "Monitor Arm", link: "monitor-arm" },
    { id: 21, name: "Keyboard Wrist Rest", link: "keyboard-wrist-rest" },
    { id: 22, name: "Mouse Pad XL", link: "mouse-pad-xl" },
    { id: 23, name: "Cable Management Kit", link: "cable-management-kit" },
    { id: 24, name: "Power Strip", link: "power-strip" },
    { id: 25, name: "UPS Battery Backup", link: "ups-battery-backup" },
    { id: 26, name: "NVMe SSD", link: "nvme-ssd" },
    { id: 27, name: "RAM 32GB", link: "ram-32gb" },
    { id: 28, name: "CPU Cooler", link: "cpu-cooler" },
    { id: 29, name: "PC Case", link: "pc-case" },
    { id: 30, name: "Motherboard", link: "motherboard" },
    { id: 31, name: "Power Supply Unit", link: "power-supply-unit" },
    { id: 32, name: "GPU RTX 4080", link: "gpu-rtx-4080" },
    { id: 33, name: "Capture Card", link: "capture-card" },
    { id: 34, name: "HDMI Cable 2.1", link: "hdmi-cable-2-1" },
    { id: 35, name: "DisplayPort Cable", link: "displayport-cable" },
    { id: 36, name: "Ethernet Switch", link: "ethernet-switch" },
    { id: 37, name: "Wi-Fi Router", link: "wi-fi-router" },
    { id: 38, name: "Network Card", link: "network-card" },
    { id: 39, name: "Portable Charger", link: "portable-charger" },
    { id: 40, name: "Wireless Charger", link: "wireless-charger" },
    { id: 41, name: "USB Flash Drive", link: "usb-flash-drive" },
    { id: 42, name: "SD Card Reader", link: "sd-card-reader" },
    { id: 43, name: "Laser Printer", link: "laser-printer" },
    { id: 44, name: "Document Scanner", link: "document-scanner" },
    { id: 45, name: "Shredder", link: "shredder" },
    { id: 46, name: "Desk Organizer", link: "desk-organizer" },
    { id: 47, name: "Monitor Riser", link: "monitor-riser" },
    { id: 48, name: "Trackball Mouse", link: "trackball-mouse" },
    { id: 49, name: "Vertical Mouse", link: "vertical-mouse" },
    { id: 50, name: "Compact Keyboard", link: "compact-keyboard" },
    { id: 51, name: "Numpad", link: "numpad" },
    { id: 52, name: "Foot Rest", link: "foot-rest" },
    { id: 53, name: "Chair Mat", link: "chair-mat" },
    { id: 54, name: "Whiteboard", link: "whiteboard" },
    { id: 55, name: "Sticky Note Dispenser", link: "sticky-note-dispenser" },
    { id: 56, name: "Label Maker", link: "label-maker" },
    { id: 57, name: "Smart Plug", link: "smart-plug" },
    { id: 58, name: "Smart Light Strip", link: "smart-light-strip" },
    { id: 59, name: "Bias Lighting Kit", link: "bias-lighting-kit" },
    { id: 60, name: "Privacy Screen Filter", link: "privacy-screen-filter" },
    { id: 61, name: "Screen Cleaning Kit", link: "screen-cleaning-kit" },
    { id: 62, name: "Anti-Glare Screen", link: "anti-glare-screen" },
    { id: 63, name: "Dual Monitor Stand", link: "dual-monitor-stand" },
    { id: 64, name: "Triple Monitor Stand", link: "triple-monitor-stand" },
    { id: 65, name: "Green Screen", link: "green-screen" },
    { id: 66, name: "Acoustic Panels", link: "acoustic-panels" },
    { id: 67, name: "Desk Shelf", link: "desk-shelf" },
    { id: 68, name: "Under Desk Drawer", link: "under-desk-drawer" },
    { id: 69, name: "Pegboard Kit", link: "pegboard-kit" },
    { id: 70, name: "Cable Raceway", link: "cable-raceway" },
    { id: 71, name: "Velcro Cable Ties", link: "velcro-cable-ties" },
    { id: 72, name: "Anti-Static Wrist Strap", link: "anti-static-wrist-strap" },
    { id: 73, name: "Compressed Air Duster", link: "compressed-air-duster" },
    { id: 74, name: "Thermal Paste", link: "thermal-paste" },
    { id: 75, name: "PC Toolkit", link: "pc-toolkit" },
    { id: 76, name: "KVM Switch", link: "kvm-switch" },
    { id: 77, name: "Video Switcher", link: "video-switcher" },
    { id: 78, name: "Audio Interface", link: "audio-interface" },
    { id: 79, name: "Studio Monitor Speakers", link: "studio-monitor-speakers" },
    { id: 80, name: "Headphone Amp", link: "headphone-amp" },
    { id: 81, name: "DAC Converter", link: "dac-converter" },
    { id: 82, name: "Boom Arm", link: "boom-arm" },
    { id: 83, name: "Pop Filter", link: "pop-filter" },
    { id: 84, name: "Shock Mount", link: "shock-mount" },
    { id: 85, name: "MIDI Controller", link: "midi-controller" },
    { id: 86, name: "Drawing Monitor", link: "drawing-monitor" },
    { id: 87, name: "VR Headset", link: "vr-headset" },
    { id: 88, name: "3D Mouse", link: "3d-mouse" },
    { id: 89, name: "Gamepad Controller", link: "gamepad-controller" },
    { id: 90, name: "Racing Wheel", link: "racing-wheel" },
    { id: 91, name: "Flight Stick", link: "flight-stick" },
    { id: 92, name: "Fingerprint Reader", link: "fingerprint-reader" },
    { id: 93, name: "Smart Card Reader", link: "smart-card-reader" },
    { id: 94, name: "Barcode Scanner", link: "barcode-scanner" },
    { id: 95, name: "Touchscreen Monitor", link: "touchscreen-monitor" },
    { id: 96, name: "E-ink Monitor", link: "e-ink-monitor" },
    { id: 97, name: "Portable Monitor", link: "portable-monitor" },
    { id: 98, name: "Projector", link: "projector" },
    { id: 99, name: "Smart Glasses", link: "smart-glasses" },
    { id: 100, name: "Holographic Display", link: "holographic-display" },
]